<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DilipK-X1" failures="2" tests="2" name="Default test(failed)" time="0.083" errors="0" timestamp="2021-10-10T18:33:40 IST">
  <testcase classname="deep.retryfailedcars.RetryFailedCare_Demo" name="test2" time="0.01">
    <failure type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
at deep.retryfailedcars.RetryFailedCare_Demo.test2(RetryFailedCare_Demo.java:17)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase classname="deep.retryfailedcars.RetryFailedCare_Demo" name="test3" time="0.004">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at deep.retryfailedcars.RetryFailedCare_Demo.test3(RetryFailedCare_Demo.java:24)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase classname="deep.retryfailedcars.RetryFailedCare_Demo" name="test1" time="0.0">
    <ignored/>
  </testcase> <!-- test1 -->
</testsuite> <!-- Default test(failed) -->
